apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: interview-wildcard-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: "*.interview.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: PLACEHOLDER
                port:
                  number: 8443
