apiVersion: v1
kind: Service
metadata:
  name: k8s-interview-room-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: interview-room
  ports:
    - name: code-server
      protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 30443
